# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cer3-Iv-Rq7omI2ruiXVyjybHhs5hU0
"""

user_input = input("Введите, пожалуйста, номер месяца: ")
month = int(user_input)
month_number = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 30,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
}
month_name = {
    1: 'январь',
    2: 'февраль',
    3: 'март',
    4: 'апрель',
    5: 'май',
    6: 'июнь',
    7: 'июль',
    8: 'август',
    9: 'сентябрь',
    10: 'октябрь',
    11: 'ноябрь',
    12: 'декабрь'

}

if month in month_number:
    print('Вы ввели', month_name[month], month_number[month], 'дней')


else:
    print("Такого номера месяца нет в году")
    print('Введите число от 1 до 12')

